feat: working mvp
MeltanoLabs/target-snowflake pull request #2
Opened 2022-09-27 14:57 UTC by kgpayne

2022-09-28 16:05 UTC, kgpayne commented on target_snowflake/sinks.py
> +                "ALTER TABLE %(table)s ALTER COLUMN %(col_name)s SET DATA TYPE %(col_type)s",
This is the only line that changed in this function compared to super(). Will raise a PR move this `ALTER` statement into a `get` method that can be overridden.

2022-10-27 18:46 UTC, aaronsteers approved these changes

2022-10-27 18:49 UTC, aaronsteers commented on target_snowflake/sinks.py
> +        Args:
Tiny nit:

```suggestion
    def _adapt_column_type(
        self,
        full_table_name: str,
        column_name: str,
        sql_type: sqlalchemy.types.TypeEngine,
    ) -> None:
        """Adapt table column type to support the new JSON schema type.

        Overridden here as Snowflake ALTER syntax for columns is different than that implemented in the SDK
        https://docs.snowflake.com/en/sql-reference/sql/alter-table-column.html
        TODO: update once https://github.com/meltano/sdk/pull/1114 merges

        Args:
```

2022-10-27 18:50 UTC, aaronsteers commented on target_snowflake/sinks.py
> +                "ALTER TABLE %(table)s ALTER COLUMN %(col_name)s SET DATA TYPE %(col_type)s",
👍 - Thanks for calling this out. Now it's in the method declaration so I'll resolve this comment.

2022-10-27 18:52 UTC, aaronsteers commented on target_snowflake/sinks.py
> +            target_type = evaluate_typemaps(type_maps, jsonschema_type, target_type)
Note to our future selves to see what can be improved upstream in the SDK to simplify and remove need to call the private `_json_schema_type_check()`

2022-10-27 18:54 UTC, aaronsteers commented on target_snowflake/sinks.py
> +            target_type = evaluate_typemaps(type_maps, jsonschema_type, target_type)
To discuss further in:

- #4 

as follow-on.

2022-10-27 19:00 UTC, aaronsteers commented on target_snowflake/sinks.py
> +        sting_submaps = [
Minor typo:

```suggestion
        string_submaps = [
```

And below when referencing the var.

2022-10-27 19:03 UTC, aaronsteers commented
@kgpayne - This looks ready to go! But please do go ahead and log any issues that you want to make sure we come back to. Even for SDK upstream changes, you can log an issue here in this repo to get the conversations started - and to represent the work that would be needed after the SDK-side updates.

A huge step from what's on `main` so I would lean towards a merge this week if we can. 🎉 

@edgarrmondragon - Any changes you'd like to see, now, or in an upcoming iteration?

2022-10-28 13:19 UTC, edgarrmondragon requested changes

2022-10-28 13:19 UTC, edgarrmondragon commented on target_snowflake/sinks.py
> +from gzip import open as gzip_open
I don't think this is used

```suggestion
```

2022-10-28 13:25 UTC, edgarrmondragon commented
@kgpayne Just a nit on an unused import, otherwise looks good.

We should probably add pre-commit to lint the repo.

2022-10-28 23:31 UTC, aaronsteers approved these changes

2022-10-28 23:32 UTC, aaronsteers commented
> @kgpayne Just a nit on an unused import, otherwise looks good.
> 
> We should probably add pre-commit to lint the repo.

Logged:

- https://github.com/MeltanoLabs/target-snowflake/issues/5

2022-10-28 23:33 UTC, edgarrmondragon approved these changes

2022-10-28 23:36 UTC, aaronsteers commented
I'm going to go ahead and merge this, and we can iterate from here.

cc @pnadolny13, @visch, @BuzzCutNorman

Follow-ups are logged in the issue tracker: https://github.com/meltanolabs/target-snowflake/issues

Nice work on this, @kgpayne

2022-10-28 23:36 UTC, merged